name: mailtrain-v3

services:

  mailtrain:

    container_name: mailtrain

    build:
      context: ./Mailtrain-V3
      dockerfile: Dockerfile

    ports:
    - "3000:3000"
    - "3003:3003"
    - "3004:3004"
    volumes:
    - Mailtrain-Files:/app/server/files

  mysql:
    image: mariadb:10.4
    environment:
    - MYSQL_ROOT_PASSWORD=mailtrain
    - MYSQL_DATABASE=mailtrain
    - MYSQL_USER=mailtrain
    - MYSQL_PASSWORD=mailtrain
    volumes:
    - MySQL-Data:/var/lib/mysql

  redis:
    image: redis:5
    volumes:
    - Redis-Data:/data


volumes:
  Mailtrain-Files: {}
  MySQL-Data: {}
  Redis-Data: {}